AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless URL Shortener (Java)

Globals:
  Function:
    Runtime: java21
    Timeout: 10
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref UrlTable

Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: url_shortener
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH

  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.example.shortener.ShortenHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        ShortenApi:
          Type: HttpApi
          Properties:
            Path: /shorten
            Method: POST

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.example.shortener.RedirectHandler::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlTable
      Events:
        RedirectApi:
          Type: HttpApi
          Properties:
            Path: /{code}
            Method: GET

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
